---
- name: install editors
  sudo: yes
  action: apt pkg="{{item}}" state=present update_cache=no
  with_items:
      - "vim-gtk"
  tags: editors

- name: install zsh
  sudo: yes
  action: apt pkg="{{item}}" state=present update_cache=no
  with_items:
      - "zsh"
  tags: zsh

- name: install hyper
  sudo: yes
  action: apt pkg="{{item}}" state=present update_cache=no
  with_items:
      - "gdebi"
      - "python-pexpect"
      - "libgconf2-4"
      - "gnome-panel"

- name: download linux_deb for hyper
  shell: sudo wget https://hyper-updates.now.sh/download/linux_deb_amd64

- name: install hyper with linux_deb_amd64
  expect: 
    command: sudo gdebi linux_deb_amd64
    responses:
      "Do you want to install the software package\\? \\[y/N\\]" : "y"
  
- shell: sudo rm linux_deb_amd64
